#!/usr/local/bin/bash

projectName=$1


echo "--| create web project"
echo "--| script dir: $dirCli"
echo " -| project name: $projectName"

shift 1

while getopts "m" o;
do
  case $o in
    m)
      mkdir $projectName && cd $projectName
      cp "$dirCli/templates/index.html" ./index.html
      cp "$dirCli/templates/main.css" ./main.css
      cp "$dirCli/templates/index.html" ./main.js
      ;;
    :)
      # echo " -| option '$o' has no value"
      ;;
  esac
done
